dist: trusty
sudo: required

language: node_js
node_js:
  - '13'
  - '12'
  - '10'
  - '9'
  - '8'

addons:
  chrome: stable
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox