dist: trusty
sudo: required

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - cd frontend
  - npm install

script:
  - cd backend
  - node server.js
  - cd ../frontend
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox