version: "3.4"
services:
  apple-map-app:
    container_name: apple-map-app
    build: './frontend'
    ports:
      - "80:80"
    networks:
      - app-network
  apple-middleware:
    container_name: apple-node
    build: './backend'
    volumes:
      - .:/usr/app/server
      - /usr/app/server/node_modules
    ports:
      - "3000:3000"
    networks:
      app-network:
        aliases:
          - backend

networks:
  app-network:
    driver: bridge

