# Generated by Django 3.0 on 2020-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genetics', models.CharField(max_length=32)),
                ('species', models.CharField(max_length=32)),
                ('finalCultivar', models.CharField(max_length=32)),
                ('synonym', models.CharField(max_length=32)),
                ('isConfirmed', models.CharField(max_length=32)),
                ('use', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('genotypes', models.IntegerField()),
                ('tree_tag_id', models.IntegerField()),
                ('propertyOwner', models.IntegerField()),
                ('treeSiteLocation', models.IntegerField()),
                ('treeLatitude', models.IntegerField()),
                ('treeLongitude', models.IntegerField()),
                ('treeHeight', models.IntegerField()),
                ('treeDripLine', models.IntegerField()),
                ('trunkDiameter', models.IntegerField()),
                ('fireBlight', models.IntegerField()),
                ('fruitHanging', models.CharField(max_length=32)),
            ],
        ),
    ]
