# Generated by Django 3.0 on 2020-02-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='propertyOwner',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='apple',
            name='treeLatitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='apple',
            name='treeLongitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='apple',
            name='treeSiteLocation',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='apple',
            name='trunkDiameter',
            field=models.FloatField(),
        ),
    ]
